<?php
header('Content-type: text/html; charset=gbk'); ;
echo '<html>' . "\r\n" . '<head>' . "\r\n" . '<title>小偷后台管理系统</title>' . "\r\n" . '<meta http-equiv="Content-Type" content="text/html; charset=gb2312">' . "\r\n" . '<link rel=\'stylesheet\' type=\'text/css\' href=\'../public/css/admin.css\'>' . "\r\n" . '<script language="JavaScript">' . "\r\n" . 'function chk(){' . "\r\n\t" . 'if(document.login.adminname.value==""){' . "\r\n\t\t" . 'alert("用户名不能为空");' . "\r\n\t\t" . 'return false;' . "\r\n\t" . '}else if(document.login.password.value==""){' . "\r\n\t\t" . 'alert("密码不能为空");' . "\r\n\t\t" . 'return false;' . "\r\n\t" . '}' . "\r\n" . '}' . "\r\n" . '</script>' . "\r\n" . '</head>' . "\r\n" . '<body>' . "\r\n" . '<style type="text/css">' . "\r\n" . '*{font-size:12px;}' . "\r\n" . '</style>' . "\r\n" . '<table width="100%" height="100%" border="0" cellpadding="0" cellspacing="0">' . "\r\n" . '  <tr>' . "\r\n" . '    <td align="center"><table width="502" border="0" align="center" cellpadding="0" cellspacing="0">' . "\r\n" . '  <tr>' . "\r\n" . '    <td><img src="../public/img/top1.gif" width="502" height="70">';
$var_92 = $_SERVER["SCRIPT_NAME"];
if(preg_match('/admin\/index/i', $var_92)){
    $var_93 = '<div class=\'loginsafe\'>您的管理目录包含admin，为了网站安全,vivi建议你在FTP里把它修改为其它名称！' . "\r\n\r\n" . '</div>';
}else{
    $var_93 = "";
}
echo $var_93; ;
echo '</td>' . "\r\n" . '  </tr>' . "\r\n" . '  <tr>' . "\r\n" . '    <td height="134" align="center" background="../public/img/top2.gif" bgcolor="#F2FFD1">' . "\r\n" . '    <form method=\'post\' action=\'login.php\' name="login">' . "\r\n" . '        <table width="400" border="0" align="right" cellpadding="0" cellspacing="4">' . "\r\n" . '          <tr>' . "\r\n" . '            <td width="74" height="25" align="center">用户名称：</td>' . "\r\n" . '            <td width="314"><input class=\'in_p\' type=\'text\' name=\'adminname\' id="adminname"onFocus="this.style.borderColor=\'#00CC00\'" onBlur="this.style.borderColor=\'#dcdcdc\'" ></td>' . "\r\n" . '          </tr>' . "\r\n" . '          <tr>' . "\r\n" . '            <td height="25" align="center">密  码：</td>' . "\r\n" . '            <td><input type=\'password\' class=\'in_p\' name=\'password\' id="password" onFocus="this.style.borderColor=\'#00CC00\'" onBlur="this.style.borderColor=\'#dcdcdc\'" ></td>' . "\r\n" . '          </tr>' . "\r\n" . '            <td height="25" align="center">&nbsp;</td>' . "\r\n" . '            <td><input name="action" type=\'hidden\' value=\'login\'><input name="submit" type=\'image\' src="../public/img/top4.gif" x=10 y=10 id="submit" class="noborder"></td>' . "\r\n" . '          </tr>' . "\r\n" . '        </table>' . "\r\n" . '    </form></td>' . "\r\n" . '  </tr>' . "\r\n" . '  <tr>' . "\r\n" . '    <td><img src="../public/img/top3.gif" width="502" height="84"></td>' . "\r\n" . '  </tr>' . "\r\n" . '</table></td>' . "\r\n" . '  </tr>' . "\r\n" . '</table>' . "\r\n" . '<span style="display:none">' . "\r\n\r\n" . '</span>' . "\r\n" . '</body>' . "\r\n" . '</html>' . "\r\n";
?>